Money::ratioOf throws exception if currencies don't match
moneyphp/money pull request #735
Opened 2023-02-04 10:09 UTC by peterdevpl

I also added a test case for `Money::mod` which already performs currency check.

fixes #732

2023-02-04 20:42 UTC, smelesh requested changes

2023-02-04 20:42 UTC, smelesh commented on tests/MoneyTest.php
> +        $money->mod($rightMoney);
it looks like `ratioOf` should be there

2023-02-04 23:31 UTC, peterdevpl commented on tests/MoneyTest.php
> +        $money->mod($rightMoney);
Good catch, fixed!

2023-02-20 20:59 UTC, frederikbosch commented
Nice catch, will merge when green checks. Thanks!

2023-02-20 20:59 UTC, merged